<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
         http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>in.ioi.pw</groupId>
    <artifactId>hibernateManyToOne</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <properties>

        <!-- Java 25 -->
        <maven.compiler.release>25</maven.compiler.release>

        <project.build.sourceEncoding>
            UTF-8
        </project.build.sourceEncoding>

        <!-- Hibernate -->
        <hibernate.version>7.1.2.Final</hibernate.version>

    </properties>


    <dependencies>

        <!-- Hibernate ORM -->
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>${hibernate.version}</version>
        </dependency>


        <!-- MySQL -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>9.4.0</version>
        </dependency>

    </dependencies>


    <build>

        <plugins>

            <!-- Java 25 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>

                <configuration>
                    <release>25</release>
                </configuration>
            </plugin>


            <!-- Run TestApp -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.0</version>

                <configuration>
                    <mainClass>in.ioi.pw.TestApp</mainClass>
                </configuration>

            </plugin>

        </plugins>

    </build>

</project>